# Configuración de Conexión usando tus variables de entorno
spring.datasource.url=jdbc:postgresql://${DB_HOST:bjb5rke598otgmcmxmz3-postgresql.services.clever-cloud.com}:${DB_PORT:5432}/${DB_NAME:bjb5rke598otgmcmxmz3}
spring.datasource.username=${DB_USERNAME:ueyjcytppo9nh9p21ph9}
spring.datasource.password=${DB_PASSWORD:iTzdJx2SBUTIbc34xUEeiMxFfiqkOC}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto de la API
server.port=8080